import './globals.css'
import { Inter } from 'next/font/google'
const { Client } = require('pg')
import Link from 'next/link'
import connection from '@/sql/connection'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Banka Uygulaması',
  description: 'Generated by create next app',
}

async function getCustomers() {
  const db = new Client(connection)
  await db.connect()
   
  const res = await db.query('select * from customer')
  
  await db.end()
  // console.log(res.rows[0])
  return res.rows
}


export default async function RootLayout({ children }) {
  const customers = await getCustomers()

  return (
    <html lang="en">
      <body className={`${inter.className} flex`} >
        <div className='flex flex-col min-h-screen gap-4 px-4 py-8 text-sm font-semibold border-r border-gray-200 shadow-xl'>
          {
            customers.map(customer => {
              return (
                <Link href={`/customer/${customer.id}`}>
                  <span className='px-2 py-1 text-indigo-700 rounded-md hover:bg-indigo-50 whitespace-nowrap' >
                    {customer.customer_name}
                  </span>
                </Link>
              )
            })
          }
          <Link href={`/transferler`} className='mt-6'>
            <span className='px-2 py-1 text-orange-700 rounded-md hover:bg-orange-50 whitespace-nowrap'>
              Para Transferleri
            </span>
          </Link>
        </div>
        <div className='flex flex-col w-full p-8' >
          <div>{children}</div>
        </div>
      </body>
    </html>
  )
}
